- hosts: all
  become: true
  tasks:
    - name: Update package index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install apache2 package
      apt:
        name: apache2
      when: ansible_distribution == "Ubuntu"

    - name: Add PHP support for apache
      apt:
        name: libapache2-mod-php
      when: ansible_distribution == "Ubuntu"
